name: update_search

on:
  push:
    branches:
      - main
      
    paths-ignore:
      - "ISSUE_TEMPLATE/**"
      - ".github/**.md"
      - ".gitignore"
      - "demo/**"
      - "docker/**"
      - "HOW_TO.md"
      - "TASK.md"
      - "SECURITY.md"
      - "README.md"
      - "README_zh-CN.md"
      
  schedule:
    #UTC 0 
    - cron: '0 0 * * *'

jobs:
  algolia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: docsearch.json -> config
        id: algolia_config
        run: echo "::set-output name=config::$(cat docsearch.json | jq -r tostring)"

      - name: algolia/docsearch-scraper 
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          CONFIG: ${{ steps.algolia_config.outputs.config }}
        run: |
          docker run \
            --env APPLICATION_ID=${ALGOLIA_APP_ID} \
            --env API_KEY=${ALGOLIA_API_KEY} \
            --env "CONFIG=${CONFIG}" \
            algolia/docsearch-scraper  
            
